relution:
  host: example.com
  token: mysupersecrettoken
mysql:
  host: example.com
  port: 3306
  user: myuser
  password: mypassword
  name: mydatabasename
ldap:
  url: https://example.com/path/to/login
port: 9000
loglevel: debug / info / warn / error